import { GetServerSideProps } from "next";
import { parseCookies } from "nookies";
import React from "react";
import Footer from "../components/Footer";
import { LoginForm } from "../components/LoginForm";
import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export default function login() {
  return (
    <div>
      <Head>
        <title>Kyoka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginForm />
      <Footer />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { ["kyoka-token"]: token } = parseCookies(ctx);

  if (!token) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: { ...(await serverSideTranslations(ctx.locale, ["common"])) },
  };
};
