import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import SRSPanel from "../components/SRSPanel";
import React from "react";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div
      id="container"
      className="flex flex-col h-screen w-screen justify-between"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <Navbar />

      {/* Container */}
      <div className="flex flex-col justify-center items-center flex-grow">
        {/* SRS Panel */}
        <SRSPanel />
      </div>
      <Footer />
    </div>
  );
}
